#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=VMUNet
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16  
#SBATCH --time=01:00:00
#SBATCH --output=slurm_out/VMUNet_%A.out

module purge
module load 2023
module load Miniconda3/23.5.2-0

source activate ai4mi

cd /home/scur2508/ai4mi_project

python main_pep.py --dataset SEGTHOR --model VMUNet --mode full --epoch 50 --dest /scratch-shared/scur2508/results/SEGTHOR_VMUNet/ --gpu